/**
 * Landing Page — hero section with project branding, animated background,
 * feature highlights, and CTA buttons.
 */

import React from 'react'
import { useNavigate } from 'react-router-dom'
import {
  HiLightningBolt,
  HiShieldCheck,
  HiChartBar,
  HiSparkles,
  HiArrowRight,
} from 'react-icons/hi'
import Navbar from '../components/Navbar'
import Button from '../components/Button'

/* ── Feature cards data ─────────────────────────────────────────────────── */
const FEATURES = [
  {
    icon: <HiLightningBolt size={24} />,
    title: 'AI-Powered Training',
    desc: 'Personalised workout plans generated by advanced AI tailored to your fitness level.',
    color: 'from-cyan-500/20 to-cyan-500/5',
    iconColor: 'text-cyan-400',
  },
  {
    icon: <HiShieldCheck size={24} />,
    title: 'Injury Prevention',
    desc: 'Real-time posture analysis and smart alerts to keep you training safely.',
    color: 'from-green-500/20 to-green-500/5',
    iconColor: 'text-green-400',
  },
  {
    icon: <HiChartBar size={24} />,
    title: 'Progress Analytics',
    desc: 'Detailed performance dashboards to track every milestone of your journey.',
    color: 'from-purple-500/20 to-purple-500/5',
    iconColor: 'text-purple-400',
  },
  {
    icon: <HiSparkles size={24} />,
    title: 'Smart Nutrition',
    desc: 'AI-driven meal recommendations aligned with your training goals.',
    color: 'from-orange-500/20 to-orange-500/5',
    iconColor: 'text-orange-400',
  },
]

/* ── Stat chips ─────────────────────────────────────────────────────────── */
const STATS = [
  { value: '10K+', label: 'Active Users' },
  { value: '95%',  label: 'Injury Reduction' },
  { value: '200+', label: 'Workout Plans' },
  { value: '4.9★', label: 'User Rating' },
]

const Landing = () => {
  const navigate = useNavigate()

  return (
    <div className="relative min-h-screen overflow-hidden">
      <Navbar variant="landing" />

      {/* ── Background FX ─────────────────────────────────────────────── */}
      <div className="orb w-[600px] h-[600px] bg-cyan-500  top-[-20%] left-[-15%]"  aria-hidden="true" />
      <div className="orb w-[500px] h-[500px] bg-green-500 bottom-[-15%] right-[-10%]" aria-hidden="true" style={{ animationDelay: '3s' }} />
      <div className="orb w-96 h-96 bg-cyan-400 top-[50%] left-[40%]" aria-hidden="true" style={{ animationDelay: '1.5s' }} />

      {/* Subtle grid */}
      <div
        className="absolute inset-0 opacity-[0.025] pointer-events-none"
        style={{
          backgroundImage:
            'linear-gradient(rgba(0,229,255,1) 1px, transparent 1px), linear-gradient(90deg, rgba(0,229,255,1) 1px, transparent 1px)',
          backgroundSize: '60px 60px',
        }}
        aria-hidden="true"
      />

      {/* ── Hero Section ──────────────────────────────────────────────── */}
      <section className="relative z-10 flex flex-col items-center justify-center text-center
                          min-h-screen px-4 pt-20 pb-10">

        {/* Badge */}
        <div className="inline-flex items-center gap-2 glass px-4 py-2 rounded-full mb-8 animate-fade-in">
          <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
          <span className="text-xs text-gray-300 tracking-wide">
            AI Powered • Production Ready • Fully Secure
          </span>
        </div>

        {/* Logo icon */}
        <div
          className="w-20 h-20 rounded-2xl bg-gradient-to-br from-cyan-500 to-green-500
                     flex items-center justify-center text-3xl font-black text-gray-950
                     shadow-2xl shadow-cyan-500/40 mb-8 animate-float glow-cyan"
          aria-hidden="true"
        >
          PT
        </div>

        {/* Title */}
        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-black leading-tight mb-4 animate-slide-up">
          <span className="gradient-text text-shadow-glow">பயிற்சித் தோழன்</span>
          <br />
          <span className="text-white">AI</span>
        </h1>

        {/* Subtitle */}
        <p className="text-lg sm:text-xl text-gray-400 max-w-xl mb-3 animate-fade-in"
           style={{ animationDelay: '0.2s' }}>
          AI Powered Fitness &amp; Injury Prevention Platform
        </p>
        <p className="text-sm text-gray-600 max-w-lg mb-12 animate-fade-in"
           style={{ animationDelay: '0.3s' }}>
          Train smarter, recover faster, and reach your peak performance with
          personalised AI guidance — available 24/7.
        </p>

        {/* CTA Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 mb-16 animate-slide-up"
             style={{ animationDelay: '0.4s' }}>
          <Button
            variant="primary"
            size="lg"
            icon={<HiArrowRight />}
            onClick={() => navigate('/signup')}
            className="min-w-[180px]"
          >
            Create Account
          </Button>
          <Button
            variant="outline"
            size="lg"
            onClick={() => navigate('/login')}
            className="min-w-[180px]"
          >
            Login
          </Button>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 max-w-2xl w-full animate-fade-in"
             style={{ animationDelay: '0.5s' }}>
          {STATS.map((s) => (
            <div key={s.label} className="glass p-4 text-center rounded-xl">
              <p className="text-2xl font-bold gradient-text">{s.value}</p>
              <p className="text-xs text-gray-500 mt-1">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features Section ──────────────────────────────────────────── */}
      <section className="relative z-10 py-20 px-4">
        <div className="max-w-5xl mx-auto">

          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
              Everything You Need to{' '}
              <span className="gradient-text">Train Better</span>
            </h2>
            <p className="text-gray-500 max-w-lg mx-auto">
              Our AI continuously learns from your performance to deliver
              increasingly precise recommendations.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className={`glass bg-gradient-to-b ${f.color} p-6 rounded-2xl
                            hover:scale-[1.03] transition-transform duration-300
                            hover:shadow-xl cursor-default`}
              >
                <div className={`${f.iconColor} mb-4`}>{f.icon}</div>
                <h3 className="font-semibold text-white text-sm mb-2">{f.title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ────────────────────────────────────────────────── */}
      <section className="relative z-10 py-20 px-4">
        <div className="max-w-3xl mx-auto text-center glass p-12 rounded-3xl
                        border border-cyan-500/10 shadow-2xl shadow-cyan-500/5">
          <h2 className="text-3xl font-bold text-white mb-4">
            Ready to Start Your{' '}
            <span className="gradient-text">Fitness Journey?</span>
          </h2>
          <p className="text-gray-500 mb-8">
            Join thousands of athletes already training with AI-powered guidance.
          </p>
          <Button
            variant="primary"
            size="lg"
            onClick={() => navigate('/signup')}
            className="shadow-2xl shadow-cyan-500/30"
          >
            Get Started Free
          </Button>
        </div>
      </section>

      {/* ── Footer ────────────────────────────────────────────────────── */}
      <footer className="relative z-10 py-8 px-4 border-t border-white/5 text-center">
        <p className="text-xs text-gray-700">
          © {new Date().getFullYear()} பயிற்சித் தோழன் AI. All rights reserved.
        </p>
      </footer>
    </div>
  )
}

export default Landing
